name: Update dist/

on:
  push:
    branches-ignore: ['update-dist--**']
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  update-dist:
    name: Update dist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Rebuild the dist/ directory
        run: |
          npm run bundle

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: 'chore(dist): update dist/ on ${{ github.ref_name }}'
          commit-message: 'chore(dist): update dist/'
          body: 'Updated dist/ built distributable files'
          branch: update-dist--${{ github.ref_name }}
          delete-branch: true
          labels: bot,dist
